[workspace]
members = [ 
  "blinky", 
  "ble/*", 
  "raw", 
  "simple",
  "thermostat",
  "workspace-hack", 
]
# metadata.crane.name = "hello-bit"
metadata.crane.version = "0.1.0"
resolver = "2"

[profile.release]
debug = 2
